// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/post": {
            "get": {
                "description": "this method can get all post",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get all post"
                ],
                "summary": "Get all posts",
                "responses": {}
            },
            "post": {
                "description": "this method can create a new post",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Create a new post",
                "parameters": [
                    {
                        "description": "Create post",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PostRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/post/:id": {
            "delete": {
                "description": "this method can delete a post",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Delete a post",
                "responses": {}
            },
            "patch": {
                "description": "this method can update a post",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Update a post",
                "parameters": [
                    {
                        "description": "Update post",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PostRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/post/id": {
            "get": {
                "description": "this method can get post by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get all post"
                ],
                "summary": "Get post by id",
                "responses": {}
            }
        }
    },
    "definitions": {
        "models.PostRequest": {
            "type": "object",
            "required": [
                "Body",
                "Title"
            ],
            "properties": {
                "Body": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 64
                },
                "Title": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 4
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Crm crud project",
	Description:      "A test sample for tutorial golang",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
