basePath: /api/v1
definitions:
  models.PostRequest:
    properties:
      Body:
        maxLength: 256
        minLength: 64
        type: string
      Title:
        maxLength: 64
        minLength: 4
        type: string
    required:
    - Body
    - Title
    type: object
host: localhost:3000
info:
  contact: {}
  description: A test sample for tutorial golang
  title: Crm crud project
  version: 1.0.0
paths:
  /post:
    get:
      description: this method can get all post
      produces:
      - application/json
      responses: {}
      summary: Get all posts
      tags:
      - Get all post
    post:
      description: this method can create a new post
      parameters:
      - description: Create post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.PostRequest'
      produces:
      - application/json
      responses: {}
      summary: Create a new post
      tags:
      - Post
  /post/:id:
    delete:
      description: this method can delete a post
      produces:
      - application/json
      responses: {}
      summary: Delete a post
      tags:
      - Post
    patch:
      description: this method can update a post
      parameters:
      - description: Update post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.PostRequest'
      produces:
      - application/json
      responses: {}
      summary: Update a post
      tags:
      - Post
  /post/id:
    get:
      description: this method can get post by id
      produces:
      - application/json
      responses: {}
      summary: Get post by id
      tags:
      - Get all post
swagger: "2.0"
